import { randomBytes } from 'node:crypto';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { digest,randomToken,error,passwordHash,passwordMatches,secretBox,base32,verifyTotp,totpCounter,RateLimiter } from './security.js';
const json=(value,status=200)=>Response.json(value,{status});
export class AuthService {
 constructor({db,env,audit,fetchImpl=fetch}){this.db=db;this.env=env;this.audit=audit;this.fetch=fetchImpl;this.vault=secretBox(env.DATA_KEY);this.loginLimits=new RateLimiter({limit:15,windowMs:15*60000});this.jwks=null;}
 migrate(){this.db.exec(`CREATE TABLE IF NOT EXISTS auth_accounts(user_id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT,role TEXT NOT NULL DEFAULT 'user',disabled INTEGER NOT NULL DEFAULT 0,mfa TEXT,mfa_pending TEXT,mfa_last INTEGER NOT NULL DEFAULT 0,backup_codes TEXT NOT NULL DEFAULT '[]');CREATE TABLE IF NOT EXISTS auth_sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL,created INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_sessions_user ON auth_sessions(user_id);CREATE TABLE IF NOT EXISTS auth_invites(hash TEXT PRIMARY KEY,email TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS auth_oidc(state TEXT PRIMARY KEY,data TEXT NOT NULL,expires INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS auth_codes(hash TEXT PRIMARY KEY,data TEXT NOT NULL,expires INTEGER NOT NULL);`);}
 async bootstrap(){if(this.db.prepare('SELECT user_id FROM auth_accounts LIMIT 1').get())return;if(!this.env.ADMIN_EMAIL||!this.env.ADMIN_PASSWORD)throw Error('Set ADMIN_EMAIL and a strong ADMIN_PASSWORD for first startup');const password=await passwordHash(this.env.ADMIN_PASSWORD),id=crypto.randomUUID(),email=this.env.ADMIN_EMAIL.toLowerCase();this.db.prepare('INSERT INTO auth_accounts(user_id,email,password,role) VALUES (?,?,?,?)').run(id,email,password,'admin');this.db.prepare('INSERT INTO users(id,email,name,created) VALUES (?,?,?,?)').run(id,email,this.env.ADMIN_NAME||'Administrator',Date.now());this.audit.append(id,'account.bootstrap','',{email});}
 user(id){const row=this.db.prepare('SELECT users.*,auth_accounts.role,auth_accounts.disabled FROM users JOIN auth_accounts ON users.id=auth_accounts.user_id WHERE users.id=?').get(id);return row&&!row.disabled?{userId:row.id,email:row.email,displayName:row.name,role:row.role}:null;}
 session(user){const token=randomToken(),expires=Date.now()+12*3600000;this.db.prepare('INSERT INTO auth_sessions VALUES (?,?,?,?)').run(digest(token),user.userId,expires,Date.now());return {token,expires,user:{id:user.userId,name:user.displayName,email:user.email,role:user.role}};}
 async authenticate(request){const authorization=request.headers?.get?request.headers.get('authorization'):request.headers?.authorization;const token=authorization?.startsWith('Bearer ')?authorization.slice(7):null;if(!token)return null;const row=this.db.prepare('SELECT user_id FROM auth_sessions WHERE hash=? AND expires>?').get(digest(token),Date.now());return row?this.user(row.user_id):null;}
 requireAdmin(user){if(user?.role!=='admin')throw error('Administrator access required',403);}
 async discovery(){if(!this.env.OIDC_ISSUER||!this.env.OIDC_CLIENT_ID)throw error('Enterprise sign-in is not configured',503);const issuer=this.env.OIDC_ISSUER.replace(/\/$/,'');if(!issuer.startsWith('https://'))throw error('OIDC issuer must use HTTPS',503);if(!this.metadata){const response=await this.fetch(issuer+'/.well-known/openid-configuration');if(!response.ok)throw error('Identity provider is unavailable',502);const data=await response.json();if(data.issuer!==issuer||!['authorization_endpoint','token_endpoint','jwks_uri'].every(k=>typeof data[k]==='string'&&data[k].startsWith('https://')))throw error('Invalid identity provider configuration',502);this.metadata=data;this.jwks=createRemoteJWKSet(new URL(data.jwks_uri));}return this.metadata;}
 async handle(request,user){const url=new URL(request.url),path=url.pathname.replace('/api/auth/','');if(!url.pathname.startsWith('/api/auth/'))return null;const body=async()=>{const text=await request.text();if(text.length>16000)throw error('Request too large',413);return JSON.parse(text);};
 if(path==='config'&&request.method==='GET')return json({oidc:!!this.env.OIDC_ISSUER,registration:'invite',mfa:true});
 if(path==='login'&&request.method==='POST'){const b=await body(),email=String(b.email||'').toLowerCase();this.loginLimits.take(email);const account=this.db.prepare('SELECT * FROM auth_accounts WHERE email=?').get(email);const valid=await passwordMatches(b.password,account?.password||'00000000000000000000000000000000:'+('0'.repeat(128)));if(!valid||!account||account.disabled){this.audit.append(email,'auth.login_rejected');throw error('Email or password is incorrect',401);}if(account.mfa){const codes=JSON.parse(account.backup_codes);const backup=codes.indexOf(digest(String(b.code||'')));if(backup>=0){codes.splice(backup,1);const claimed=this.db.prepare('UPDATE auth_accounts SET backup_codes=? WHERE user_id=? AND backup_codes=?').run(JSON.stringify(codes),account.user_id,account.backup_codes);if(!claimed.changes)throw error('Recovery code was already used',401);}else{const counter=totpCounter(this.vault.open(account.mfa),b.code);if(counter===null||counter<=account.mfa_last)throw error('A valid unused authenticator or recovery code is required',401);const claimed=this.db.prepare('UPDATE auth_accounts SET mfa_last=? WHERE user_id=? AND mfa_last<?').run(counter,account.user_id,counter);if(!claimed.changes)throw error('Authenticator code was already used',401);}}const authenticated=this.user(account.user_id);this.audit.append(authenticated.userId,'auth.login');return json(this.session(authenticated));}
 if(path==='register'&&request.method==='POST'){const b=await body();this.loginLimits.take('invite:'+digest(String(b.invite)));const invite=this.db.prepare('SELECT * FROM auth_invites WHERE hash=? AND expires>? AND used=0').get(digest(String(b.invite)),Date.now());if(!invite)throw error('Invitation is invalid or expired',403);if(this.db.prepare('SELECT user_id FROM auth_accounts WHERE email=?').get(invite.email))throw error('This account already exists',409);const hash=await passwordHash(b.password),id=crypto.randomUUID();this.db.exec('BEGIN IMMEDIATE');try{const claim=this.db.prepare('UPDATE auth_invites SET used=1 WHERE hash=? AND used=0').run(invite.hash);if(!claim.changes)throw error('Invitation has already been used',409);this.db.prepare('INSERT INTO auth_accounts(user_id,email,password) VALUES (?,?,?)').run(id,invite.email,hash);this.db.prepare('INSERT INTO users VALUES (?,?,?,?)').run(id,invite.email,String(b.name||invite.email).slice(0,120),Date.now());this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}this.audit.append(id,'account.register');return json(this.session(this.user(id)),201);}
 if(path==='oidc/start'&&request.method==='POST'){const b=await body();if(!/^[A-Za-z0-9_-]{43}$/.test(b.challenge||''))throw error('A PKCE challenge is required');const metadata=await this.discovery(),state=randomToken(),nonce=randomToken(),verifier=randomToken(),challenge=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))).toString('base64url');const data={nonce,verifier,clientChallenge:b.challenge};this.db.prepare('INSERT INTO auth_oidc VALUES (?,?,?)').run(digest(state),this.vault.seal(data),Date.now()+10*60000);const redirect=this.env.PUBLIC_URL+'/api/auth/oidc/callback',login=new URL(metadata.authorization_endpoint);for(const [k,v]of Object.entries({response_type:'code',client_id:this.env.OIDC_CLIENT_ID,redirect_uri:redirect,scope:'openid email profile',state,nonce,code_challenge:challenge,code_challenge_method:'S256'}))login.searchParams.set(k,v);return json({url:login.href});}
 if(path==='oidc/callback'&&request.method==='GET'){const state=digest(url.searchParams.get('state')||''),row=this.db.prepare('DELETE FROM auth_oidc WHERE state=? AND expires>? RETURNING *').get(state,Date.now());if(!row)throw error('Sign-in expired; please try again',401);const data=this.vault.open(row.data),metadata=await this.discovery();const fields={grant_type:'authorization_code',client_id:this.env.OIDC_CLIENT_ID,code:url.searchParams.get('code')||'',code_verifier:data.verifier,redirect_uri:this.env.PUBLIC_URL+'/api/auth/oidc/callback'};if(this.env.OIDC_CLIENT_SECRET)fields.client_secret=this.env.OIDC_CLIENT_SECRET;const response=await this.fetch(metadata.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});if(!response.ok)throw error('Enterprise sign-in failed',401);const tokens=await response.json(),{payload}=await jwtVerify(tokens.id_token,this.jwks,{issuer:metadata.issuer,audience:this.env.OIDC_CLIENT_ID});if(payload.nonce!==data.nonce||!payload.email||payload.email_verified!==true)throw error('A verified email identity is required',403);const email=String(payload.email).toLowerCase();let account=this.db.prepare('SELECT * FROM auth_accounts WHERE email=?').get(email);if(!account){const domains=(this.env.OIDC_ALLOWED_DOMAINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!domains.includes(email.split('@')[1]))throw error('Your organization has not granted access',403);const id=crypto.randomUUID();this.db.prepare('INSERT INTO auth_accounts(user_id,email,password) VALUES (?,?,NULL)').run(id,email);this.db.prepare('INSERT INTO users VALUES (?,?,?,?)').run(id,email,String(payload.name||email),Date.now());account={user_id:id};}const authenticated=this.user(account.user_id);if(!authenticated)throw error('Account is disabled',403);const code=randomToken();this.db.prepare('INSERT INTO auth_codes VALUES (?,?,?)').run(digest(code),this.vault.seal({userId:authenticated.userId,challenge:data.clientChallenge}),Date.now()+60000);const target=new URL(this.env.FRONTEND_URL||this.env.PUBLIC_URL);target.hash='auth='+code;this.audit.append(authenticated.userId,'auth.oidc');return Response.redirect(target.href,303);}
 if(path==='exchange'&&request.method==='POST'){const b=await body(),row=this.db.prepare('SELECT * FROM auth_codes WHERE hash=? AND expires>?').get(digest(String(b.code)),Date.now());if(!row)throw error('Sign-in code expired',401);const data=this.vault.open(row.data),challenge=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(b.verifier)))).toString('base64url');if(challenge!==data.challenge)throw error('Invalid sign-in verifier',403);const claimed=this.db.prepare('DELETE FROM auth_codes WHERE hash=?').run(row.hash);if(!claimed.changes)throw error('Sign-in code was already used',401);const authenticated=this.user(data.userId);if(!authenticated)throw error('Account is disabled',403);return json(this.session(authenticated));}
 if(!user)throw error('Sign in required',401);
 if(path==='me'&&request.method==='GET'){const a=this.db.prepare('SELECT mfa FROM auth_accounts WHERE user_id=?').get(user.userId);return json({user,mfa:!!a?.mfa});}
 if(path==='logout'&&request.method==='POST'){const token=request.headers.get('authorization')?.slice(7);this.db.prepare('DELETE FROM auth_sessions WHERE hash=?').run(digest(token||''));return json({ok:true});}
 if(path==='sessions/revoke'&&request.method==='POST'){this.db.prepare('DELETE FROM auth_sessions WHERE user_id=?').run(user.userId);this.audit.append(user.userId,'auth.revoke_all');return json({ok:true});}
 if(path==='mfa/setup'&&request.method==='POST'){const b=await body(),account=this.db.prepare('SELECT * FROM auth_accounts WHERE user_id=?').get(user.userId);if(account.mfa)throw error('MFA is already enabled',409);if(!await passwordMatches(b.password,account.password))throw error('Confirm your password',403);const secret=base32(randomBytes(20));this.db.prepare('UPDATE auth_accounts SET mfa_pending=? WHERE user_id=?').run(this.vault.seal(secret),user.userId);return json({secret,uri:`otpauth://totp/Avenor:${encodeURIComponent(user.email)}?secret=${secret}&issuer=Avenor`});}
 if(path==='mfa/confirm'&&request.method==='POST'){const b=await body(),account=this.db.prepare('SELECT * FROM auth_accounts WHERE user_id=?').get(user.userId);if(!account.mfa_pending||!verifyTotp(this.vault.open(account.mfa_pending),b.code))throw error('Enter a valid authenticator code');const codes=Array.from({length:8},()=>randomBytes(6).toString('hex'));this.db.prepare('UPDATE auth_accounts SET mfa=mfa_pending,mfa_pending=NULL,backup_codes=? WHERE user_id=?').run(JSON.stringify(codes.map(digest)),user.userId);this.audit.append(user.userId,'auth.mfa_enabled');return json({recoveryCodes:codes});}
 if(path==='invitations'&&request.method==='POST'){this.requireAdmin(user);const b=await body(),email=String(b.email||'').toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw error('A valid email address is required');const token=randomToken();this.db.prepare('INSERT INTO auth_invites VALUES (?,?,?,0)').run(digest(token),email,Date.now()+7*86400000);this.audit.append(user.userId,'account.invite','',{email});return json({invite:token,email,expires:Date.now()+7*86400000},201);}
 if(path==='users'&&request.method==='GET'){this.requireAdmin(user);return json({users:this.db.prepare('SELECT users.id,users.email,users.name,auth_accounts.role,auth_accounts.disabled FROM users JOIN auth_accounts ON users.id=auth_accounts.user_id').all()});}
 if(path==='users'&&request.method==='PATCH'){this.requireAdmin(user);const b=await body();if(b.id===user.userId)throw error('Use another administrator to change your own access');if(!['user','admin'].includes(b.role))throw error('Invalid role');this.db.prepare('UPDATE auth_accounts SET role=?,disabled=? WHERE user_id=?').run(b.role,b.disabled?1:0,b.id);this.db.prepare('DELETE FROM auth_sessions WHERE user_id=?').run(b.id);this.audit.append(user.userId,'account.access_changed','',{id:b.id,role:b.role,disabled:!!b.disabled});return json({ok:true});}
 return json({error:'Unknown authentication route'},404);
 }
}
