import { error } from './security.js';
export class Permissions {
 constructor({db,audit,emit=()=>{}}){this.db=db;this.audit=audit;this.emit=emit;db.exec(`CREATE TABLE IF NOT EXISTS delegations(scope TEXT NOT NULL,user_id TEXT NOT NULL,permissions TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(scope,user_id));CREATE TABLE IF NOT EXISTS policies(scope TEXT PRIMARY KEY,retention_days INTEGER NOT NULL DEFAULT 0,legal_hold INTEGER NOT NULL DEFAULT 0,updated INTEGER NOT NULL);`);}
 scopes(user){return this.db.prepare('SELECT scope,permissions FROM delegations WHERE user_id=?').all(user.userId);}
 async authorize({user,scope,recordId,action='read'}){if(!user)return false;if(recordId){const record=this.db.prepare('SELECT * FROM records WHERE id=? AND deleted=0').get(recordId);if(!record||scope&&record.scope!==scope)return false;scope=record.scope;if(action==='write'&&record.kind==='message'){const data=JSON.parse(record.data);if(data.delivery==='submitting')return false;}}
 if(!scope)return false;if(scope==='user:'+user.userId)return true;
 const read=['read','subscribe','view','list','read-jobs','read-notifications','read-invitation','respond-invitation'].includes(action);if(scope.startsWith('team:')){const m=this.db.prepare('SELECT role FROM members WHERE team=? AND user=?').get(scope.slice(5),user.userId);if(!m)return false;if(read)return true;if(m.role==='viewer')return false;if(action==='admin')return m.role==='owner';return ['owner','editor'].includes(m.role);}
 const d=this.db.prepare('SELECT permissions FROM delegations WHERE scope=? AND user_id=?').get(scope,user.userId);if(!d)return false;const grants=JSON.parse(d.permissions);return grants.includes(read?'read':action==='send'||action==='schedule-send'||action==='invite'?'send':'write');}
 async require(args){if(!await this.authorize(args))throw error('You do not have permission for this action',403);}
 async handle(request,user){const url=new URL(request.url);if(!['/api/delegations','/api/policies','/api/team/role'].includes(url.pathname))return null;if(!user)throw error('Sign in required',401);const b=request.method==='GET'?Object.fromEntries(url.searchParams):await request.json();if(url.pathname==='/api/delegations'){const scope='user:'+user.userId;if(request.method==='GET')return Response.json({delegations:this.db.prepare('SELECT delegations.*,users.email,users.name FROM delegations JOIN users ON users.id=delegations.user_id WHERE scope=?').all(scope)});const target=this.db.prepare('SELECT id FROM users WHERE lower(email)=?').get(String(b.email||'').toLowerCase());if(!target||target.id===user.userId)throw error('Choose another registered account');if(request.method==='DELETE')this.db.prepare('DELETE FROM delegations WHERE scope=? AND user_id=?').run(scope,target.id);else{const permissions=[...new Set(b.permissions||[])];if(!permissions.length||permissions.some(x=>!['read','write','send'].includes(x)))throw error('Select valid delegation permissions');if(!permissions.includes('read'))permissions.unshift('read');this.db.prepare('INSERT INTO delegations VALUES (?,?,?,?) ON CONFLICT(scope,user_id) DO UPDATE SET permissions=excluded.permissions').run(scope,target.id,JSON.stringify(permissions),Date.now());}this.audit.append(user.userId,'delegation.changed',scope,{target:target.id,permissions:b.permissions||[]});this.emit(scope,{type:'permissions-changed'});return Response.json({ok:true});}
 if(url.pathname==='/api/team/role'){await this.require({user,scope:'team:'+b.team,action:'admin'});if(!['viewer','editor'].includes(b.role))throw error('Choose viewer or editor');const team=this.db.prepare('SELECT owner FROM teams WHERE id=?').get(b.team);if(team.owner===b.user)throw error('Workspace owner role cannot be changed');this.db.prepare('UPDATE members SET role=? WHERE team=? AND user=?').run(b.role,b.team,b.user);this.audit.append(user.userId,'team.role','team:'+b.team,{user:b.user,role:b.role});this.emit('team:'+b.team,{type:'permissions-changed'});return Response.json({ok:true});}
 const scope=b.scope||'user:'+user.userId;if(scope!=='user:'+user.userId)await this.require({user,scope,action:'admin'});if(request.method==='GET')return Response.json({policy:this.db.prepare('SELECT * FROM policies WHERE scope=?').get(scope)||{scope,retention_days:0,legal_hold:0}});const days=Number(b.retentionDays);if(!Number.isInteger(days)||days<0||days>36500)throw error('Retention must be between 0 and 36,500 days');this.db.prepare('INSERT INTO policies VALUES (?,?,?,?) ON CONFLICT(scope) DO UPDATE SET retention_days=excluded.retention_days,legal_hold=excluded.legal_hold,updated=excluded.updated').run(scope,days,b.legalHold?1:0,Date.now());this.audit.append(user.userId,'policy.changed',scope,{retentionDays:days,legalHold:!!b.legalHold});return Response.json({ok:true});}
}
