import { randomBytes, createHash, createCipheriv, createDecipheriv, timingSafeEqual, scrypt as scryptCallback, createHmac } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCallback);
export const digest=value=>createHash('sha256').update(value).digest('hex');
export const randomToken=()=>randomBytes(32).toString('base64url');
export const error=(message,status=400)=>Object.assign(new Error(message),{status});
export function secretBox(key){const bytes=Buffer.from(key||'','base64');if(bytes.length!==32)throw Error('DATA_KEY must contain 32 random bytes encoded as base64');return {seal(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',bytes,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64');},open(value){const blob=Buffer.from(value,'base64'),cipher=createDecipheriv('aes-256-gcm',bytes,blob.subarray(0,12));cipher.setAuthTag(blob.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(blob.subarray(28)),cipher.final()]).toString('utf8'));}};}
export async function passwordHash(password){if(typeof password!=='string'||password.length<12||password.length>1024)throw error('Use a password between 12 and 1,024 characters');const salt=randomBytes(16).toString('hex');const value=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});return `${salt}:${value.toString('hex')}`;}
export async function passwordMatches(password,stored){if(typeof password!=='string'||password.length>1024||!stored)return false;const [salt,expected]=stored.split(':');const actual=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});return expected?.length===128&&timingSafeEqual(actual,Buffer.from(expected,'hex'));}
export function base32(bytes){let bits=0,value=0,output='';const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){output+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)output+=alphabet[(value<<(5-bits))&31];return output;}
function unbase32(value){let bits=0,buffer=0,out=[];for(const c of value.toUpperCase().replace(/=+$/,'')){const v='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);if(v<0)throw Error('Invalid MFA secret');buffer=(buffer<<5)|v;bits+=5;if(bits>=8){out.push((buffer>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
export function totp(secret,at=Date.now()){const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(at/30000)));const mac=createHmac('sha1',unbase32(secret)).update(counter).digest();const offset=mac[19]&15;return ((mac.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');}
export function totpCounter(secret,code,now=Date.now()){if(!/^\d{6}$/.test(String(code)))return null;for(const n of [0,-1,1])if(timingSafeEqual(Buffer.from(totp(secret,now+n*30000)),Buffer.from(String(code))))return Math.floor(now/30000)+n;return null;}
export function verifyTotp(secret,code,now=Date.now()){return totpCounter(secret,code,now)!==null;}
export class AuditLog {
 constructor(db){this.db=db;db.exec('CREATE TABLE IF NOT EXISTS audit_log (sequence INTEGER PRIMARY KEY AUTOINCREMENT,created INTEGER NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,scope TEXT NOT NULL,detail TEXT NOT NULL,previous TEXT NOT NULL,hash TEXT NOT NULL)');}
 append(actor,action,scope='',detail={}){const last=this.db.prepare('SELECT hash FROM audit_log ORDER BY sequence DESC LIMIT 1').get();const data={created:Date.now(),actor:String(actor||'system'),action,scope,detail:JSON.stringify(detail),previous:last?.hash||''};data.hash=digest(JSON.stringify(data));this.db.prepare('INSERT INTO audit_log(created,actor,action,scope,detail,previous,hash) VALUES (?,?,?,?,?,?,?)').run(...Object.values(data));return data.hash;}
 verify(){let previous='';for(const row of this.db.prepare('SELECT * FROM audit_log ORDER BY sequence').all()){const data={created:row.created,actor:row.actor,action:row.action,scope:row.scope,detail:row.detail,previous:row.previous};if(row.previous!==previous||digest(JSON.stringify(data))!==row.hash)return {valid:false,sequence:row.sequence};previous=row.hash;}return {valid:true,head:previous};}
}
export class RateLimiter {constructor({limit=120,windowMs=60000}={}){this.limit=limit;this.windowMs=windowMs;this.entries=new Map();}take(key){const now=Date.now();let entry=this.entries.get(key);if(!entry||entry.until<=now)this.entries.set(key,entry={count:0,until:now+this.windowMs});if(++entry.count>this.limit)throw error('Too many requests. Please try again shortly.',429);if(this.entries.size>10000)for(const [k,v]of this.entries)if(v.until<now)this.entries.delete(k);}}
