import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, readFileSync, writeFileSync, renameSync, existsSync, unlinkSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { randomUUID, createCipheriv, createDecipheriv } from 'node:crypto';
export function openDatabase(filename){if(filename!==':memory:')mkdirSync(resolve(filename,'..'),{recursive:true,mode:0o700});const db=new DatabaseSync(filename);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');db.exec('CREATE TABLE IF NOT EXISTS backend_migrations (name TEXT PRIMARY KEY, applied INTEGER NOT NULL)');const initial='0000_warm_stick';if(!db.prepare('SELECT name FROM backend_migrations WHERE name=?').get(initial)){db.exec('BEGIN IMMEDIATE');try{db.exec(readFileSync(new URL('../drizzle/0000_warm_stick.sql',import.meta.url),'utf8'));db.prepare('INSERT INTO backend_migrations VALUES (?,?)').run(initial,Date.now());db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}}db.exec('CREATE INDEX IF NOT EXISTS idx_users_email ON users(email); CREATE INDEX IF NOT EXISTS idx_records_scope_deleted_id ON records(scope,deleted,id); CREATE UNIQUE INDEX IF NOT EXISTS idx_teams_invite ON teams(invite)');return db;}
export function asD1(db){return {prepare(sql){const statement=db.prepare(sql);let args=[];return {bind(...values){args=values;return this;},async first(){return statement.get(...args)||null;},async all(){return {results:statement.all(...args)};},runSync(){const result=statement.run(...args);return {meta:{changes:Number(result.changes),last_row_id:Number(result.lastInsertRowid)}};},async run(){return this.runSync();}};},async batch(statements){db.exec('BEGIN IMMEDIATE');try{const results=statements.map(statement=>statement.runSync());db.exec('COMMIT');return results;}catch(error){db.exec('ROLLBACK');throw error;}}};}
export class FileBucket {
 constructor(directory,key){this.directory=resolve(directory);this.key=key?Buffer.from(key,'base64'):null;if(this.key&&this.key.length!==32)throw Error('DATA_KEY must be a base64-encoded 32-byte key');mkdirSync(this.directory,{recursive:true,mode:0o700});}
 path(id){if(!/^[a-zA-Z0-9:_-]{1,250}$/.test(id))throw Error('Invalid file identifier');return join(this.directory,id);}
 async put(id,data){const bytes=Buffer.from(data instanceof ReadableStream?await new Response(data).arrayBuffer():data);let output=bytes;if(this.key){const iv=Buffer.from(crypto.getRandomValues(new Uint8Array(12))),cipher=createCipheriv('aes-256-gcm',this.key,iv);output=Buffer.concat([Buffer.from('AVN1'),iv,cipher.update(bytes),cipher.final(),cipher.getAuthTag()]);}const tmp=this.path(id)+'.'+randomUUID()+'.tmp';writeFileSync(tmp,output,{mode:0o600});renameSync(tmp,this.path(id));}
 async get(id){if(!existsSync(this.path(id)))return null;let bytes=readFileSync(this.path(id));if(bytes.subarray(0,4).toString()==='AVN1'){if(!this.key)throw Error('DATA_KEY is required to read encrypted attachments');const decipher=createDecipheriv('aes-256-gcm',this.key,bytes.subarray(4,16));decipher.setAuthTag(bytes.subarray(-16));bytes=Buffer.concat([decipher.update(bytes.subarray(16,-16)),decipher.final()]);}return {body:new Blob([bytes]).stream(),arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};}
 async head(id){const obj=await this.get(id);return obj?{size:(await obj.arrayBuffer()).byteLength}:null;}
 async delete(id){try{unlinkSync(this.path(id));}catch(error){if(error.code!=='ENOENT')throw error;}}
}
