import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handle} from '../server/engine.js';
import {matches,occurrences,toEml,toIcs,escapeHtml} from '../public/core.js';
class D1 {constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../drizzle/0000_warm_stick.sql',import.meta.url),'utf8'));}prepare(sql){const db=this.sqlite;let args=[];return {bind(...values){args=values;return this;},async all(){return {results:db.prepare(sql).all(...args)};},async first(){return db.prepare(sql).get(...args)||null;},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}async batch(statements){this.sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());this.sqlite.exec('COMMIT');return out;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}}
class R2 {constructor(){this.files=new Map();}async put(id,data){this.files.set(id,data instanceof ReadableStream?new Uint8Array(await new Response(data).arrayBuffer()):new Uint8Array(data));}async get(id){const data=this.files.get(id);return data?{body:new Blob([data]).stream()}:null;}async head(id){return this.files.has(id)?{size:this.files.get(id).length}:null;}async delete(id){this.files.delete(id);}}
const alice={userId:'alice',email:'alice@example.com',displayName:'Alice Test'},bob={userId:'bob',email:'bob@example.com',displayName:'Bob Test'},eve={userId:'eve',email:'eve@example.com',displayName:'Eve Test'};
function fixture(){const env={DB:new D1(),BUCKET:new R2()};return {env,async req(path,method='GET',body,who=alice,headers={}){const response=await handle(new Request('https://avenor.example/api/'+path,{method,headers:{'content-type':'application/json',origin:'https://avenor.example',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}),env,who);const data=await response.json();return {status:response.status,data};},async create(kind,data,scope='user:alice',who=alice){return this.req('record','POST',{kind,data,scope},who);}};}
const draft=(patch={})=>({folder:'drafts',date:new Date().toISOString(),to:bob.email,cc:'',bcc:'',subject:'Hello',body:'<p>Hello teammate</p>',attachments:[],...patch});
async function teamFixture(){const f=fixture();await f.req('data');await f.req('data','GET',undefined,bob);await f.req('data','GET',undefined,eve);const {data:team}=await f.req('team','POST',{action:'create',name:'Studio'});await f.req('team','POST',{action:'join',invite:team.invite},bob);return {...f,team};}
test('Authentication required for all API data',async()=>{const f=fixture();assert.equal((await f.req('data','GET',undefined,null)).status,401);});
test('Bootstrap is durable and idempotent',async()=>{const f=fixture(),a=await f.req('data'),b=await f.req('data');assert.equal(a.status,200);assert.equal(a.data.records.length,29);assert.equal(a.data.records.length,b.data.records.length);assert.equal(new Set(a.data.records.map(r=>r.id)).size,a.data.records.length);});
test('Cross-origin writes rejected',async()=>{const f=fixture();const r=await f.req('record','POST',{kind:'task',data:{title:'Bad'},scope:'user:alice'},alice,{origin:'https://evil.example'});assert.equal(r.status,403);});
test('Private records cannot be read, edited, or removed by others',async()=>{const f=fixture(),{data:record}=await f.create('task',{title:'Private'});assert.equal((await f.req('data?scope=user:alice','GET',undefined,bob)).status,403);assert.equal((await f.req('record','PATCH',{id:record.id,version:1,patch:{title:'Hijack'}},bob)).status,404);assert.equal((await f.req('record','DELETE',{id:record.id,version:1},bob)).status,404);});
test('Optimistic update rejects stale writes and preserves winning content',async()=>{const f=fixture(),{data:r}=await f.create('task',{title:'Original'});const a=await f.req('record','PATCH',{id:r.id,version:1,patch:{title:'Winner'}});const b=await f.req('record','PATCH',{id:r.id,version:1,patch:{title:'Stale'}});assert.equal(a.status,200);assert.equal(b.status,409);assert.equal(JSON.parse((await f.env.DB.prepare('SELECT data FROM records WHERE id=?').bind(r.id).first()).data).title,'Winner');});
test('Reject malformed shared data and injection categories',async()=>{const f=fixture();assert.equal((await f.create('task',{title:42})).status,400);assert.equal((await f.create('task',{title:'x',steps:{a:1}})).status,400);assert.equal((await f.create('contact',{name:42})).status,400);assert.equal((await f.create('event',{title:'x',start:'2026-09-12T10:00Z',end:'2026-09-12T11:00Z',category:'x" onmouseover="alert(1)'})).status,400);assert.equal((await f.create('event',{title:'x',start:'2026-09-12T12:00Z',end:'2026-09-12T11:00Z'})).status,400);});
test('Shared workspace invites grant scoped access and revocation takes effect',async()=>{const f=await teamFixture();const {data:r}=await f.create('task',{title:'Shared'},'team:'+f.team.id);const read=await f.req('data?scope=team:'+f.team.id,'GET',undefined,bob);assert.ok(read.data.records.some(x=>x.id===r.id));assert.equal((await f.req('data?scope=team:'+f.team.id,'GET',undefined,eve)).status,403);assert.equal((await f.req('team','POST',{action:'remove',team:f.team.id,user:bob.userId})).status,200);assert.equal((await f.req('record','PATCH',{id:r.id,version:1,patch:{title:'No longer allowed'}},bob)).status,404);});
test('Only owners rotate invites; old invitations expire on rotation',async()=>{const f=await teamFixture();assert.equal((await f.req('team','POST',{action:'invite',team:f.team.id},bob)).status,403);assert.equal((await f.req('team','POST',{action:'invite',team:f.team.id})).status,200);assert.equal((await f.req('team','POST',{action:'join',invite:f.team.invite},eve)).status,404);});
test('Comment author and parent cannot be changed by patch',async()=>{const f=await teamFixture();const {data:parent}=await f.create('task',{title:'Shared'},'team:'+f.team.id);const {data:c}=await f.create('comment',{parent:parent.id,body:'A note',author:'Spoof'},'team:'+f.team.id);assert.equal(c.author,'Alice Test');const result=await f.req('record','PATCH',{id:c.id,version:1,patch:{body:'Edited',author:'Bob',authorId:'bob',parent:'unknown'}});assert.equal(result.data.author,'Alice Test');assert.equal(result.data.parent,parent.id);assert.equal((await f.req('record','PATCH',{id:c.id,version:2,patch:{body:'Hijack'}},bob)).status,403);});
test('Internal mail sends atomically, strips Bcc, and rejects duplicate send',async()=>{const f=await teamFixture();const {data:r}=await f.create('message',draft({bcc:alice.email}));const result=await f.req('send','POST',{id:r.id,version:r.version});assert.equal(result.status,200);assert.equal(result.data.folder,'sent');assert.equal((await f.req('send','POST',{id:r.id,version:r.version})).status,400);const data=await f.req('data','GET',undefined,bob),delivered=data.data.records.filter(x=>x.id===r.id+':delivery:bob');assert.equal(delivered.length,1);assert.equal(delivered[0].bcc,undefined);assert.equal(delivered[0].read,false);});
test('External recipient failure preserves draft and makes no partial delivery',async()=>{const f=await teamFixture();const {data:r}=await f.create('message',draft({to:bob.email+',outside@example.com'}));const result=await f.req('send','POST',{id:r.id,version:r.version});assert.equal(result.status,409);assert.equal(JSON.parse((await f.env.DB.prepare('SELECT data FROM records WHERE id=?').bind(r.id).first()).data).folder,'drafts');assert.equal(await f.env.DB.prepare('SELECT id FROM records WHERE id=?').bind(r.id+':delivery:bob').first(),null);});
test('Upload enforces size and attachment ownership scope',async()=>{const f=await teamFixture();const form=new FormData();form.set('file',new File(['hello'],'notes.txt',{type:'text/plain'}));form.set('scope','user:alice');const response=await handle(new Request('https://avenor.example/api/upload',{method:'POST',body:form}),f.env,alice);assert.equal(response.status,201);const file=await response.json();const shared=await f.create('message',draft({attachments:[file]}),'team:'+f.team.id);assert.equal(shared.status,403);const privateMessage=await f.create('message',draft({attachments:[file]}));assert.equal(privateMessage.status,201);const other=await handle(new Request('https://avenor.example/api/file/'+file.id),f.env,bob);assert.equal(other.status,404);});
test('Attachment bytes are copied into recipient-owned storage',async()=>{const f=await teamFixture();const form=new FormData();form.set('file',new File(['hello attachment'],'notes.txt',{type:'text/plain'}));const upload=await handle(new Request('https://avenor.example/api/upload',{method:'POST',body:form}),f.env,alice),file=await upload.json();const {data:r}=await f.create('message',draft({attachments:[file]}));assert.equal((await f.req('send','POST',{id:r.id,version:1})).status,200);const received=(await f.req('data','GET',undefined,bob)).data.records.find(x=>x.id===r.id+':delivery:bob');assert.notEqual(received.attachments[0].id,file.id);const response=await handle(new Request('https://avenor.example/api/file/'+received.attachments[0].id),f.env,bob);assert.equal(await response.text(),'hello attachment');});
test('Missing attachment bytes prevent send and preserve draft',async()=>{const f=await teamFixture();const form=new FormData();form.set('file',new File(['hello'],'notes.txt'));const upload=await handle(new Request('https://avenor.example/api/upload',{method:'POST',body:form}),f.env,alice),file=await upload.json();const {data:r}=await f.create('message',draft({attachments:[file]}));await f.env.BUCKET.delete(file.id);assert.equal((await f.req('send','POST',{id:r.id,version:1})).status,409);assert.equal(JSON.parse((await f.env.DB.prepare('SELECT data FROM records WHERE id=?').bind(r.id).first()).data).folder,'drafts');});
test('Pagination exposes all records without duplicates',async()=>{const f=fixture();await f.req('data');for(let i=0;i<505;i++)await f.create('task',{title:'Task '+i});const first=await f.req('data');assert.equal(first.data.records.length,500);assert.ok(first.data.nextCursor);const second=await f.req('data?cursor='+encodeURIComponent(first.data.nextCursor));assert.equal(second.data.nextCursor,null);assert.equal(first.data.records.length+second.data.records.length,534);assert.equal(new Set([...first.data.records,...second.data.records].map(r=>r.id)).size,534);});
test('Search combines sender, subject, unread and attachment filters',()=>{const m={from:'alice@example.com',to:'bob@example.com',subject:'Launch plans',body:'<p>Autumn release</p>',read:false,attachments:[{id:'a'}]};assert.ok(matches(m,'from:alice subject:launch is:unread has:attachment'));assert.ok(matches(m,'subject:"Launch plans"'));assert.ok(!matches(m,'is:read'));assert.ok(!matches(m,'from:other'));});
test('Daily recurrence seeks into older series',()=>{const result=occurrences({start:'2025-01-01T10:00:00Z',end:'2025-01-01T11:00:00Z',repeat:'daily'},new Date('2026-09-12'),new Date('2026-09-13'));assert.equal(result.length,1);assert.equal(result[0].start,'2026-09-12T10:00:00.000Z');});
test('Recurrence obeys inclusive until and skips nonexistent monthly dates',()=>{const result=occurrences({start:'2026-09-01T10:00:00Z',end:'2026-09-01T11:00:00Z',repeat:'daily',until:'2026-09-02'},new Date('2026-09-01'),new Date('2026-09-05'));assert.equal(result.length,2);const monthly=occurrences({start:'2026-01-31T10:00:00Z',end:'2026-01-31T11:00:00Z',repeat:'monthly'},new Date('2026-01-01'),new Date('2026-05-01'));assert.deepEqual(monthly.map(x=>x.start.slice(0,10)),['2026-01-31','2026-03-31']);});
test('MIME export preserves Cc/Bcc, unicode and attachment bytes',()=>{const output=toEml(draft({from:alice.email,cc:'cc@example.com',bcc:'bcc@example.com',subject:'Hello ✨',attachments:[{name:'test.txt',type:'text/plain',base64:'aGVsbG8='}]}));assert.match(output,/Cc: cc@example.com/);assert.match(output,/Bcc: bcc@example.com/);assert.match(output,/multipart\/mixed/);assert.match(output,/aGVsbG8=/);assert.match(output,/Subject: =\?UTF-8\?B\?/);assert.throws(()=>toEml(draft({attachments:[{id:'unloaded'}]})),/Attachment bytes/);});
test('Calendar export preserves recurrence and escapes structured fields',()=>{const output=toIcs([{id:'1',title:'Plan, review; next',start:'2026-09-12T10:00Z',end:'2026-09-12T11:00Z',repeat:'weekly',until:'2026-10-12'}]);assert.match(output,/RRULE:FREQ=WEEKLY;UNTIL=20261012T235959Z/);assert.ok(output.includes('SUMMARY:Plan\\, review\\; next'));assert.equal(escapeHtml('<script>'), '&lt;script&gt;');});
test('Request body size is enforced without trusting Content-Length',async()=>{const f=fixture();const r=await f.req('record','POST',{kind:'task',data:{title:'x',notes:'x'.repeat(181000)}});assert.equal(r.status,413);});
test('IANA timezone recurrence preserves local time through DST',()=>{const result=occurrences({start:'2026-03-01T09:00:00Z',end:'2026-03-01T10:00:00Z',repeat:'daily',timezone:'Europe/London'},new Date('2026-04-01'),new Date('2026-04-02'));assert.equal(result[0].start,'2026-04-01T08:00:00.000Z');});
