import { seedData } from './seed.js';
const kinds=new Set(['message','event','task','contact','folder','rule','comment','settings']);
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const uid=()=>crypto.randomUUID();
const unpack=r=>({...JSON.parse(r.data),id:r.id,kind:r.kind,scope:r.scope,version:r.version,updated:r.updated,owner:r.owner});
function clean(kind,data){
if(!data||typeof data!=='object'||Array.isArray(data))fail('Invalid record');
const d=JSON.parse(JSON.stringify(data));for(const k of ['id','kind','scope','version','updated','owner','__proto__','constructor'])delete d[k];
if(JSON.stringify(d).length>150000)fail('Record is too large',413);
for(const key of ['title','name','email','phone','company','role','notes','subject','body','to','cc','bcc','from','color','initials','category','location','attendees','repeat','until','due','reminder','assignee','signature','parent','field','contains','target','author','authorId','timezone'])if(d[key]!==undefined&&typeof d[key]!=='string')fail('Invalid '+key);
for(const key of ['read','flagged','pinned','focused','sample','favorite','important','myDay','done','allDay'])if(d[key]!==undefined&&typeof d[key]!=='boolean')fail('Invalid '+key);
if(d.category&&!['Design','Projects','Marketing','Team','Focus'].includes(d.category))fail('Invalid category');
if(d.color&&!['lavender','blue','rose','green','orange','me'].includes(d.color))fail('Invalid color');
if(d.attachments!==undefined&&(!Array.isArray(d.attachments)||d.attachments.some(a=>!a||typeof a!=='object'||typeof a.id!=='string')))fail('Invalid attachments');
if(kind==='message'){
 if(!['inbox','drafts','sent','archive','deleted','junk','outbox',...(typeof d.folder==='string'&&d.folder.startsWith('custom:')?[d.folder]:[])].includes(d.folder))fail('Invalid folder');
 if(!d.date||!Number.isFinite(+new Date(d.date)))fail('Invalid message date');
}
if(['event','task','folder','rule'].includes(kind)&&(!d.title?.trim()||d.title.length>500))fail('A title is required');
if(kind==='event'){
 if(d.timezone){try{new Intl.DateTimeFormat('en-US',{timeZone:d.timezone});}catch{fail('Invalid timezone');}}
 if(!Number.isFinite(+new Date(d.start))||!(new Date(d.end)>new Date(d.start)))fail('End time must be after the start');
 if(!['none','daily','weekly','monthly'].includes(d.repeat||'none'))fail('Invalid recurrence');
 if(d.until&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.until)||new Date(d.until+'T23:59:59')<new Date(d.start)))fail('Invalid recurrence end date');
}
if(kind==='task'){
 if(d.steps!==undefined&&(!Array.isArray(d.steps)||d.steps.length>200||d.steps.some(x=>!x||typeof x.title!=='string'||typeof x.done!=='boolean')))fail('Invalid task steps');
 if(d.due&&!/^\d{4}-\d{2}-\d{2}$/.test(d.due))fail('Invalid due date');
 if(d.reminder&&!Number.isFinite(+new Date(d.reminder)))fail('Invalid reminder');
}
if(kind==='rule'&&(!['from','subject'].includes(d.field)||!d.contains?.trim()||!['archive','deleted','junk','read','flag'].includes(d.target)&&!d.target?.startsWith('custom:')))fail('Invalid inbox rule');
if(kind==='contact'&&!d.name?.trim())fail('A contact name is required');
if(kind==='comment'&&(!d.parent||!d.body?.trim()))fail('Write a comment first');
return d;
}
async function boundedBody(request,limit){if(!request.body)return new Uint8Array();const reader=request.body.getReader(),chunks=[];let length=0;while(true){const {done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>limit){await reader.cancel();fail('Request is too large',413);}chunks.push(value);}const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
export async function handle(request,env,user){try{if(!user) return json({error:'Sign in to open your workspace',signin:'/signin-with-chatgpt?return_to=/'},401);if(!env.DB)fail('Your workspace database is temporarily unavailable. Please retry.',503);const db=env.DB,url=new URL(request.url),path=url.pathname.replace(/^\/api\/?/,'');if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin&&origin!==url.origin&&!(env.ALLOWED_ORIGINS||[]).includes(origin))fail('This request must come from Avenor',403);if(Number(request.headers.get('content-length')||0)>12*1024*1024)fail('File is too large',413);}
const mine='user:'+user.userId;const memberships=(await db.prepare('SELECT teams.id,teams.name,teams.owner,members.role FROM teams JOIN members ON teams.id=members.team WHERE members.user=?').bind(user.userId).all()).results;
const allowed=new Set([mine,...memberships.map(t=>'team:'+t.id),...(env.DELEGATED_SCOPES||[])]);const scopeOk=s=>{if(!allowed.has(s))fail('You do not have access to this workspace',403);return s;};
const read=async id=>{const r=await db.prepare('SELECT * FROM records WHERE id=? AND deleted=0').bind(id).first();if(!r||!allowed.has(r.scope))fail('Record not found',404);return r;};
const body=async()=>{const bytes=await boundedBody(request,180000);try{return JSON.parse(new TextDecoder().decode(bytes));}catch{fail('Invalid JSON');}};
const validateAttachments=async (data,scope)=>{if((data.attachments||[]).length>20)fail('Maximum 20 attachments');for(const a of data.attachments||[]){const f=await db.prepare('SELECT * FROM files WHERE id=?').bind(a.id).first();if(!f||!allowed.has(f.scope)||f.scope!==scope)fail('Attachment must belong to this workspace',403);a.name=f.name;a.size=f.size;a.type=f.type;}};
if(path==='data'&&request.method==='GET'){
await db.prepare('INSERT INTO users (id,email,name,created) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name').bind(user.userId,user.email.toLowerCase(),user.fullName||user.displayName||user.email,Date.now()).run();
const seeded=await db.prepare('SELECT id FROM records WHERE id=?').bind(user.userId+':seed').first();if(!seeded){const sample=env.SEED_SAMPLE_DATA==='false'?[]:seedData(user);await db.batch([...sample.map((r,i)=>db.prepare('INSERT OR IGNORE INTO records (id,owner,scope,kind,data,version,updated,deleted) VALUES (?,?,?,?,?,1,?,0)').bind(user.userId+':sample:'+i,user.userId,mine,r.kind,JSON.stringify(r.data),Date.now())),db.prepare('INSERT OR IGNORE INTO records (id,owner,scope,kind,data,version,updated,deleted) VALUES (?,?,?,?,?,1,?,0)').bind(user.userId+':seed',user.userId,mine,'settings',JSON.stringify({title:'Preferences',signature:'',showSamples:true}),Date.now())]);}
const scope=scopeOk(url.searchParams.get('scope')||mine);const page=(await db.prepare('SELECT * FROM records WHERE scope=? AND deleted=0 AND id>? ORDER BY id LIMIT 501').bind(scope,url.searchParams.get('cursor')||'').all()).results;const rows=page.slice(0,500);let members=[];if(scope.startsWith('team:')){await db.prepare('UPDATE members SET seen=? WHERE team=? AND user=?').bind(Date.now(),scope.slice(5),user.userId).run();members=(await db.prepare('SELECT users.id,users.name,users.email,members.role,members.seen FROM users JOIN members ON users.id=members.user WHERE members.team=?').bind(scope.slice(5)).all()).results;}
return json({user:{id:user.userId,email:user.email,name:user.fullName||user.displayName||user.email},scope,teams:memberships,members,records:rows.map(unpack),serverTime:Date.now(),nextCursor:page.length>500?rows.at(-1).id:null});}
if(path==='record'&&request.method==='POST'){const b=await body();if(!kinds.has(b.kind))fail('Unknown record type');const scope=scopeOk(b.scope||mine);const data=clean(b.kind,b.data);await validateAttachments(data,scope);if(b.kind==='comment'){const parent=await read(data.parent);if(parent.scope!==scope)fail('Comment must belong to the same workspace');data.author=user.fullName||user.displayName||user.email;data.authorId=user.userId;data.date=new Date().toISOString();}const id=env.OPERATION_ID||uid();const now=Date.now();await db.prepare('INSERT INTO records (id,owner,scope,kind,data,version,updated,deleted) VALUES (?,?,?,?,?,1,?,0)').bind(id,user.userId,scope,b.kind,JSON.stringify(data),now).run();return json({...data,id,kind:b.kind,owner:user.userId,scope,version:1,updated:now},201);}
if(path==='record'&&request.method==='PATCH'){const b=await body(),r=await read(b.id);if(r.kind==='comment'&&r.owner!==user.userId)fail('Only the author can edit this comment',403);const data=clean(r.kind,{...JSON.parse(r.data),...b.patch});await validateAttachments(data,r.scope);if(r.kind==='comment'){const old=JSON.parse(r.data);data.author=old.author;data.authorId=old.authorId;data.date=old.date;data.parent=old.parent;}if(!Number.isInteger(b.version))fail('A record version is required');const now=Date.now();const result=await db.prepare('UPDATE records SET data=?,version=version+1,updated=? WHERE id=? AND version=? AND deleted=0').bind(JSON.stringify(data),now,r.id,b.version).run();if(!result.meta.changes)fail('Someone updated this item. Your changes are still here; reload it and try again.',409);return json({...data,id:r.id,scope:r.scope,kind:r.kind,owner:r.owner,version:b.version+1,updated:now});}
if(path==='record'&&request.method==='DELETE'){const b=await body(),r=await read(b.id);if(r.kind==='comment'&&r.owner!==user.userId)fail('Only the author can remove this comment',403);const res=await db.prepare('UPDATE records SET deleted=1,updated=?,version=version+1 WHERE id=? AND version=?').bind(Date.now(),r.id,b.version).run();if(!res.meta.changes)fail('This item changed. Refresh before deleting.',409);return json({ok:true});}
if(path==='send'&&request.method==='POST'){
const b=await body(),r=await read(b.id),m=JSON.parse(r.data);if(r.kind!=='message'||!['drafts','outbox'].includes(m.folder))fail('Open a draft to send');const addresses=[...new Set([m.to,m.cc,m.bcc].filter(Boolean).flatMap(s=>s.split(/[,;]+/)).map(s=>s.trim().toLowerCase()).filter(Boolean))];if(!addresses.length||addresses.length>50||addresses.some(s=>!/^\S+@\S+\.\S+$/.test(s)))fail('Enter valid recipient email addresses (maximum 50)');if(!m.subject?.trim())fail('Add a subject before sending');const recipients=[];for(const email of addresses){const found=(await db.prepare('SELECT id,email FROM users WHERE email=?').bind(email).all()).results;const memberIds=new Set([user.userId,...(await db.prepare('SELECT DISTINCT m2.user FROM members m1 JOIN members m2 ON m1.team=m2.team WHERE m1.user=?').bind(user.userId).all()).results.map(x=>x.user)]);const target=found.find(x=>memberIds.has(x.id));if(!target)fail('External mail is not connected. Send to a registered Avenor teammate, or save this draft and export it as .eml.',409);recipients.push(target);}
await validateAttachments(m,r.scope);const now=Date.now(),date=new Date(now).toISOString();const sent={...m,folder:'sent',from:user.email,name:user.fullName||user.displayName||user.email,date,read:true,sample:false,delivery:'internal'};
if(!Number.isInteger(b.version)||b.version!==r.version)fail('Draft changed. Review the latest version before sending.',409);
for(const attachment of m.attachments||[]){if(!env.BUCKET)fail('Attachment storage is unavailable',503);if(!await env.BUCKET.head(attachment.id))fail('An attachment is missing. Remove it and upload it again before sending.',409);}
const staged=[];const statements=[db.prepare('UPDATE records SET data=?,version=version+1,updated=? WHERE id=? AND version=? AND deleted=0').bind(JSON.stringify(sent),now,r.id,b.version)];
// Deliveries are conditioned on the exact version claimed by this send, and deterministic IDs prevent duplicate delivery on retries.
try{for(const recipient of recipients){const incoming={...structuredClone(sent),folder:'inbox',read:false,bcc:undefined};for(const a of incoming.attachments||[]){const original=await db.prepare('SELECT * FROM files WHERE id=?').bind(a.id).first();const deliveryFileId=uid();statements.push(db.prepare('INSERT OR IGNORE INTO files (id,owner,scope,name,type,size,created) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM records WHERE id=? AND version=? AND data=?)').bind(deliveryFileId,recipient.id,'user:'+recipient.id,original.name,original.type,original.size,now,r.id,b.version+1,JSON.stringify(sent)));if(!env.BUCKET)fail('Attachment storage is unavailable',503);const bytes=await env.BUCKET.get(a.id);if(!bytes)fail('An attachment is missing. Remove it and upload it again before sending.',409);await env.BUCKET.put(deliveryFileId,bytes.body);staged.push(deliveryFileId);a.id=deliveryFileId;}
statements.push(db.prepare('INSERT OR IGNORE INTO records (id,owner,scope,kind,data,version,updated,deleted) SELECT ?,?,?,\'message\',?,1,?,0 WHERE EXISTS (SELECT 1 FROM records WHERE id=? AND version=? AND data=?)').bind(r.id+':delivery:'+recipient.id,recipient.id,'user:'+recipient.id,JSON.stringify(incoming),now,r.id,b.version+1,JSON.stringify(sent)));}}catch(error){for(const id of staged)await env.BUCKET.delete(id);throw error;}
let results;try{results=await db.batch(statements);}catch(error){for(const id of staged)await env.BUCKET.delete(id);throw error;}if(!results[0].meta.changes){for(const id of staged)await env.BUCKET.delete(id);fail('Draft changed. Review the latest version before sending.',409);}return json({...sent,id:r.id,kind:r.kind,scope:r.scope,owner:r.owner,version:b.version+1,updated:now});}
if(path==='team'&&request.method==='POST'){const b=await body();if(b.action==='create'){if(!String(b.name||'').trim())fail('Name your workspace');const id=uid(),invite=uid()+uid();await db.batch([db.prepare('INSERT INTO teams (id,name,owner,invite,expires) VALUES (?,?,?,?,?)').bind(id,String(b.name).slice(0,100),user.userId,invite,Date.now()+7*86400000),db.prepare('INSERT INTO members (team,user,role,seen) VALUES (?,?,?,?)').bind(id,user.userId,'owner',Date.now())]);return json({id,name:b.name,invite});}if(b.action==='join'){const t=await db.prepare('SELECT * FROM teams WHERE invite=? AND expires>?').bind(b.invite,Date.now()).first();if(!t)fail('This invitation is invalid or expired',404);await db.prepare('INSERT OR IGNORE INTO members (team,user,role,seen) VALUES (?,?,?,?)').bind(t.id,user.userId,'editor',Date.now()).run();return json({id:t.id,name:t.name});}if(b.action==='invite'){const t=memberships.find(t=>t.id===b.team);if(!t||t.owner!==user.userId)fail('Only the workspace owner can create invitations',403);const invite=uid()+uid();await db.prepare('UPDATE teams SET invite=?,expires=? WHERE id=?').bind(invite,Date.now()+7*86400000,t.id).run();return json({invite,expires:Date.now()+7*86400000});}if(b.action==='remove'){const t=memberships.find(t=>t.id===b.team);if(!t||t.owner!==user.userId||b.user===user.userId)fail('Only the owner can remove another member',403);await db.prepare('DELETE FROM members WHERE team=? AND user=?').bind(b.team,b.user).run();return json({ok:true});}fail('Unknown workspace action');}
if(path==='upload'&&request.method==='POST'){if(!env.BUCKET)fail('Attachment storage is unavailable',503);const uploadBytes=await boundedBody(request,11*1024*1024);const form=await new Request(request.url,{method:'POST',headers:request.headers,body:uploadBytes}).formData(),file=form.get('file'),scope=scopeOk(String(form.get('scope')||mine));if(!file||typeof file==='string'||!file.size||file.size>10*1024*1024)fail('Choose a file up to 10 MB');const id=uid(),name=file.name.replace(/[\r\n\\/]/g,'_').slice(0,255);await env.BUCKET.put(id,file.stream(),{httpMetadata:{contentType:'application/octet-stream'}});try{await db.prepare('INSERT INTO files (id,owner,scope,name,type,size,created) VALUES (?,?,?,?,?,?,?)').bind(id,user.userId,scope,name,file.type||'application/octet-stream',file.size,Date.now()).run();}catch(error){await env.BUCKET.delete(id);throw error;}return json({id,name,type:file.type,size:file.size},201);}
if(path.startsWith('file/')&&request.method==='GET'){const f=await db.prepare('SELECT * FROM files WHERE id=?').bind(decodeURIComponent(path.slice(5))).first();if(!f||!allowed.has(f.scope))fail('Attachment not found',404);const obj=await env.BUCKET.get(f.id);if(!obj)fail('Attachment unavailable',404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
return json({error:'Endpoint not found'},404);
}catch(error){if(!error.status)console.error('Avenor request failed',error);return json({error:error.status?error.message:'Your workspace could not be updated. Please try again.'},error.status||500);}}
