export function seedData(user){const now=new Date();now.setHours(9,0,0,0);const day=(n,h=10)=>{const d=new Date(now);d.setDate(d.getDate()+n);d.setHours(h);return d.toISOString();};const people=[['Olivia Bennett','olivia@northstar.example','OB','lavender','Design Director'],['Alex Morgan','alex@northstar.example','AM','blue','Product Manager'],['Sofia Chen','sofia@northstar.example','SC','rose','Product Designer'],['Daniel Kim','daniel@northstar.example','DK','green','Engineering Lead'],['Emma Wilson','emma@northstar.example','EW','orange','Marketing Lead'],['James Foster','james@northstar.example','JF','lavender','Co-founder'],['Maya Patel','maya@northstar.example','MP','rose','People Operations']];
const msgs=[
[0,'A little direction for our next chapter','Hi there,\n\nI’ve pulled together the brand direction for our autumn launch. The idea is simple: a little more clarity, a little more personality, and a lot more room to grow.\n\nHere’s what’s ready for your eyes:\n• Updated visual identity and color palette\n• Early explorations for the new website\n• A first look at the launch campaign\n\nI’d love to hear what resonates with you before our design review this afternoon. No need for a polished response — your first impressions are exactly what we need.\n\nThanks,\nOlivia','Design',true],
[1,'Product sync · a few things for tomorrow','Hey team,\n\nSharing a quick agenda for tomorrow’s product sync. We’ll walk through the roadmap, review customer feedback, and agree on the next milestones.\n\nPlease add anything you’d like to cover.\n\nAlex','Projects',true],
[2,'Website explorations are ready ✨','The first round of explorations is ready for review. I went with a quieter layout and a more confident typographic direction. Let me know what you think!','Design',false],
[3,'Re: September release checklist','All the remaining checks are green. We’re ready for the release review whenever you are.\n\nDaniel','Projects',true],
[4,'Autumn launch — campaign timeline','I’ve updated the timeline with our latest milestones. The creative review is on Wednesday and final assets are due Friday.','Marketing',false],
[5,'A good week. Thank you, everyone.','Just a quick note to say thank you for the care you’ve put into this week. The progress is looking wonderful. Enjoy your weekend!','',false],
[6,'Your September team update','Here’s what’s happening across the team this month: new faces, upcoming events, and a few moments worth celebrating.','Team',false],
[0,'Design system / component updates','The component library is now updated with the new navigation, form fields, and accessibility improvements.','Design',false],
[1,'Customer interviews: key takeaways','The top requests were clearer navigation, a faster way to find things, and more flexible collaboration. Notes are ready for review.','Projects',false],
[3,'API integration notes','I’ve documented the endpoint contracts and added examples for the new integration. Happy to walk through them together.','Projects',false],
[4,'Coffee next week?','Would love to catch up next week and compare notes on the launch. Tuesday morning works well for me.','',false],
[2,'A few references I thought you’d like','Found some lovely examples of editorial layouts that might be useful for the project. Saving them here for our next chat.','Design',false]
];const messages=msgs.map((m,i)=>({kind:'message',data:{from:people[m[0]][1],name:people[m[0]][0],initials:people[m[0]][2],color:people[m[0]][3],to:user.email,subject:m[1],body:m[2].split('\n\n').map(p=>'<p>'+p.replaceAll('\n','<br>')+'</p>').join(''),folder:'inbox',read:!m[4],flagged:i===0||i===3,pinned:i===0,category:m[3],date:day(-Math.floor(i/5),10-i%5),focused:i<9,sample:true,attachments:[]}}));
return [...messages,...people.map(p=>({kind:'contact',data:{name:p[0],email:p[1],initials:p[2],color:p[3],company:'Northstar Studio',role:p[4],phone:'',favorite:true,sample:true}})),...[[0,11,'Design review','Studio · Design team','Design'],[0,14,'Product catch-up','Video meeting','Projects'],[0,16,'Focus time','Personal','Focus'],[1,10,'Weekly planning','Studio · Team','Team'],[2,13,'Launch campaign','Video meeting','Marketing']].map(x=>({kind:'event',data:{title:x[2],start:day(x[0],x[1]),end:day(x[0],x[1]+1),location:x[3],category:x[4],repeat:'none',attendees:'',notes:'',sample:true}})),...['Review brand explorations','Send feedback on the roadmap','Plan next week’s priorities','Read customer interview notes'].map((t,i)=>({kind:'task',data:{title:t,due:day(i>1?2:0).slice(0,10),done:false,important:i===0,myDay:i<3,notes:'',steps:[],assignee:'',sample:true}}))];}
